### ISSUE TITLE
Create the fetch client route

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/clinic-api#18]
We need to create a route the fetches the client's details for the clinic, refer to this issue https://github.com/WebAhead12/clinic-admin/issues/7 that @julio1703 is working. [this issue](https://github.com/WebAhead12/clinic-admin/issues/7) has how the response data should look like when the clinic frontend requests for the data. 

there are multiple queries here, @Iz1cK might be able to help with this (if there are any questions), since he is building the adding a client route.

**Comment by halakhamis07** [comment]
do you need the protocols also?
